-- Añadir columnas a la tabla de usuarios
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS address TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS postal_code TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '' NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT now() NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL;